[package]
name = "public_key_bls12_381_note"
type = "lib"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.52.0", directory = "noir-projects/aztec-nr/aztec" }
