[package]
name = "bls12_381_account"
type = "contract"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.52.0", directory = "noir-projects/aztec-nr/aztec" }
public_key_bls12_381_note = { path = "../public_key_bls12_381_note" }
